---
title: "Resources"
description: |
  Hopefully one day this page becomes a vast ocean of resources for learning data science and all things programming.
---

## Books about data science with R

- [R for Data Science](https://r4ds.had.co.nz/)

- [R for Data Science Exercise Solutions](https://jrnold.github.io/r4ds-exercise-solutions/)

- [Advanced R](https://adv-r.hadley.nz/)

- [R Packages](https://r-pkgs.org/)

- [What They Forgot to Teach You About R](https://rstats.wtf/index.html)

- [Functional Programming](https://dcl-prog.stanford.edu/)

- [Mastering Shiny](https://adv-r.hadley.nz/)

- [Mastering Software Development in R](https://bookdown.org/rdpeng/RProgDA/)

- [Hands-On Machine Learning with R](https://bradleyboehmke.github.io/HOML/)

- [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/)

- [Text Mining with R](https://www.tidytextmining.com/index.html)

- [Forecasting: Principles and Practice](https://otexts.com/fpp2/)

- [Feature Engineering and Selection](http://www.feat.engineering/)

- [Interactive web-based data visualization with R, plotly, and shiny](https://plotly-r.com/index.html)

- [Happy Git and GitHub for the UseR](https://happygitwithr.com/)

- [Mastering Spark with R](https://therinspark.com/intro.html)

## R programming concepts

### Tidy eval

- [Programming with dplyr](https://dplyr.tidyverse.org/articles/programming.html)

- [Using ggplot2 in packages](https://ggplot2.tidyverse.org/articles/ggplot2-in-packages.html)

## Packages

- [tidyverse](https://www.tidyverse.org/) - all the things

- [tidymodels](https://www.tidymodels.org/) - a modeling framework that follows the same design principles and philosophies as the tidyverse

- [plumber] - build web APIs with R code

## Web stuff

- [HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP) (docs)

### JavaScript

- [fetch API](https://youtu.be/cuEtnrL9-H0) (YouTube video)

- [promises](https://youtu.be/DHvZLI7Db8E) (YouTube video)

- [async & await](https://youtu.be/V_Kr9OSfDeU) (YouTube video)

















## Cheat Sheets

- [R Programming](https://rstudio.cloud/learn/cheat-sheets)

